name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get GitHub Actions Runner Public IP
        id: get_ip
        run: |
          echo "Fetching GitHub Actions Runner public IP"
          runner_ip=$(curl -s https://api.ipify.org)
          echo "Runner Public IP: $runner_ip"
          echo "runner_ip=$runner_ip" >> $GITHUB_ENV
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add GitHub Actions IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ env.runner_ip }}/32  # 수정된 부분
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Oracle JDBC driver
        run: |
          curl -L -o ojdbc6.jar https://path/to/download/ojdbc6.jar
          mvn install:install-file -Dfile=ojdbc6.jar -DgroupId=com.oracle -DartifactId=ojdbc6 -Dversion=12.1.0.2 -Dpackaging=jar


      - name: Build with Maven
        run: mvn clean package
        working-directory: ./Project-final

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          source: "Project-final/target/*.jar"
          target: "${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/app.jar"
          key: ${{ secrets.SSH_KEY }}
      
      - name: SSH to EC2 and deploy JAR
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          debug: true
          script: |
            echo "Stopping application"
            sudo sh /usr/local/tomcat9/bin/shutdown.sh
            echo "Deploying new JAR"
            mv /home/${{ secrets.USER }}/app.jar /usr/local/tomcat9/webapps/app.jar
            echo "Starting application"
            sudo sh /usr/local/tomcat9/bin/startup.sh

      - name: Remove GitHub Actions IP from Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ env.runner_ip }}/32  # 수정된 부분
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
